#!/usr/bin/with-contenv bash

echo "=== Starting ffserver finish ==="

if [ ! -f ${var_path}/${SLINGER_VAR} ]; then
    echo " ${var_path}/${SLINGER_VAR} configuration file not found - exit 125 to prevent restart"
    echo "=== Exiting ffserver finish - 125 ==="
    exit 125
fi

echo "=== Exiting ffserver finish ==="
