#!/usr/bin/with-contenv bash

echo "=== Starting slinger run ==="

if [ -z "${SLINGER_VAR}" ]; then
    echo "=== Exiting slinger run - due to SLINGER variable not set ==="
    exit 0
fi

if [ "$ARCH_VAR" == "amd64" ]; then
  ARCH_VAR=linux-x86_64
elif [ "$ARCH_VAR" == "arm64" ]; then
  ARCH_VAR=linux-aarch64
elif [ "$ARCH_VAR" == "arm" ]; then
  ARCH_VAR=linux-arm
fi

echo " ARCH_VAR=${ARCH_VAR}"

#test if PATH_VAR is zero length or not set, if so use default, if not use the passed variable
if [ -z "${PATH_VAR}" ]; then
   var_path="/tmp"
else
   var_path="${PATH_VAR}"
fi

if [ -f  ${var_path}/${SLINGER_VAR} ]; then
    echo " configuration file exists"
    python3 -u ${var_path}/slingbox_server.py ${var_path}/${SLINGER_VAR}
fi

ffserver -hide_banner -loglevel ${FFSERVER_LOG_LEVEL} &
echo "=== Exiting slinger run ==="
