#!/usr/bin/with-contenv bash

echo "=== Starting ffserver run ==="

ffserver_exec=$(which ffserver)
echo "${ffserver_exec}"

if [ ! -f "${ffserver_exec}" ]; then
    echo "=== Exiting ffserver run - unable to locate executable ==="
    exit 0
fi

echo " ARCH_VAR=${ARCH_VAR}"

#test if FFSERVER_LOG_LEVEL is zero length or not set, if so use default, if not use the passed variable
if [ -z "${FFSERVER_LOG_LEVEL}" ]; then
   var_path=""
else
   var_path="${FFSERVER_LOG_LEVEL}"
fi

ffserver -hide_banner -loglevel ${FFSERVER_LOG_LEVEL}
echo "=== Exiting ffserver run ==="
