#!/usr/bin/with-contenv bash

echo "=== Starting ffmpg_stream run ==="

if [ -z "${SLINGER_VAR}" ]; then
    echo "=== Exiting slinger run - due to SLINGER variable not set ==="
    exit 0
fi

if [ "$ARCH_VAR" == "amd64" ]; then
  ARCH_VAR=linux-x86_64
elif [ "$ARCH_VAR" == "arm64" ]; then
  ARCH_VAR=linux-aarch64
elif [ "$ARCH_VAR" == "arm" ]; then
  ARCH_VAR=linux-arm
fi

echo " ARCH_VAR=${ARCH_VAR}"

#test if PATH_VAR is zero length or not set, if so use default, if not use the passed variable
if [ -z "${PATH_VAR}" ]; then
   var_path="/tmp"
else
   var_path="${PATH_VAR}"
fi

if [ -f  ${var_path}/${SLINGER_VAR} ]; then
    echo " configuration file exists"
    python3 -u ${var_path}/slingbox_server.py ${var_path}/${SLINGER_VAR}
fi

ffmpeg -hide_banner -loglevel ${FFMPEG_LOG_LEVEL} -rtsp_transport tcp ${FFMPEG_INPUT_OPTS} -i ${RTSP_URL} ${FFMPEG_OUTPUT_OPTS} http://127.0.0.1:8090/feed.ffm
echo "=== Exiting ffmpg_stream run ==="


