#!/usr/bin/with-contenv bash

echo "=== Starting ffmpg_stream run ==="

echo " ARCH_VAR=${ARCH_VAR}"

#test if FFMPEG_LOG_LEVEL is zero length or not set, if so use default, if not use the passed variable
if [ -z "${FFMPEG_LOG_LEVEL}" ]; then
   var_path=""
else
   var_path="${FFMPEG_LOG_LEVEL}"
fi

#test if FFMPEG_INPUT_OPTS is zero length or not set, if so use default, if not use the passed variable
if [ -z "${FFMPEG_INPUT_OPTS}" ]; then
   var_path=""
else
   var_path="${FFMPEG_INPUT_OPTS}"
fi

#test if RTSP_URL is zero length or not set, if so use default, if not use the passed variable
if [ -z "${RTSP_URL}" ]; then
   var_path=""
else
   var_path="${RTSP_URL}"
fi

#test if FFMPEG_OUTPUT_OPTS is zero length or not set, if so use default, if not use the passed variable
if [ -z "${FFMPEG_OUTPUT_OPTS}" ]; then
   var_path=""
else
   var_path="${FFMPEG_OUTPUT_OPTS}"
fi

echo "ffmpege -hide_banner -loglevel ${FFMPEG_LOG_LEVEL} -rtsp_transport tcp ${FFMPEG_INPUT_OPTS} -i ${RTSP_URL} ${FFMPEG_OUTPUT_OPTS} http://127.0.0.1:8090/feed.ffm"

ffmpege -hide_banner -loglevel ${FFMPEG_LOG_LEVEL} -rtsp_transport tcp ${FFMPEG_INPUT_OPTS} -i ${RTSP_URL} ${FFMPEG_OUTPUT_OPTS} http://127.0.0.1:8090/feed.ffm
echo "=== Exiting ffmpg_stream run ==="


