#!/usr/bin/with-contenv bash

echo "=== Starting slinger finish ==="

if [ "$ARCH_VAR" == "amd64" ]; then
  ARCH_VAR=linux-x86_64
elif [ "$ARCH_VAR" == "arm64" ]; then
  ARCH_VAR=linux-aarch64
elif [ "$ARCH_VAR" == "arm" ]; then
  ARCH_VAR=linux-arm
fi

echo " ARCH_VAR=${ARCH_VAR}"
ARCH_VAR="${ARCH_VAR}-static"

#test if PATH_VAR is zero length or not set, if so use default, if not use the passed variable
if [ -z "${PATH_VAR}" ]; then
   var_path="/tmp"
else
   var_path="${PATH_VAR}"
fi

if [ ! -f ${var_path}/${SLINGER_VAR} ]; then
    echo " ${var_path}/${SLINGER_VAR} configuration file not found - exit 125 to prevent restart"
    echo "=== Exiting aircast finish - 125 ==="
    exit 125
fi

echo "=== Exiting slinger finish ==="
