#!/usr/bin/with-contenv bash

echo "=== Starting aircast run ==="

if [ "${AIRCAST_VAR}" == "kill" ]; then
    echo "=== Exiting aircast run - due to AIRCAST variable set to \"kill\" ==="
    exit 0
fi

if [ "$ARCH_VAR" == "amd64" ]; then
  ARCH_VAR=linux-x86_64
elif [ "$ARCH_VAR" == "arm64" ]; then
  ARCH_VAR=linux-aarch64
elif [ "$ARCH_VAR" == "arm" ]; then
  ARCH_VAR=linux-arm
fi

echo " ARCH_VAR=${ARCH_VAR}"
ARCH_VAR="${ARCH_VAR}-static"

if [ -f  ]; then
    echo " executable  exists"
    if [ -z "${SLINGER_VAR}" ]; then
       # default command
       python3 -u ${SLINGER_APP}/slingbox_server.py ${SLINGER_CONF}/config.ini
    else
       # custom command
       python3 -u ${SLINGER_APP}/slingbox_server.py ${SLINGER_CONF}/config.ini
    fi
fi

#!/bin/bash

SLINGER_FILE=${SLINGER_CONF}/slinger.txt

if [ -f "$SLINGER_FILE" ]; then
	. $SLINGER_FILE
else
	#Copy sample files to /config volume if they don't already exist, does not override existing files
	cp -n ${SLINGER_APP}/sample_slinger.txt ${SLINGER_CONF}/sample_slinger.txt
	cp -n ${SLINGER_APP}/sample_xmltv.xml ${SLINGER_CONF}/sample_xmltv.xml
	cp -n ${SLINGER_APP}/slingbox.m3u ${SLINGER_CONF}/sample_slingbox.m3u
	cp -n ${SLINGER_APP}/unified_config.ini ${SLINGER_CONF}/sample_unified_config.ini
	cp -n ${SLINGER_APP}/config.ini ${SLINGER_CONF}/sample_config.ini
	cp -n ${SLINGER_APP}/config.ini ${SLINGER_CONF}/config.ini
	cp -n ${SLINGER_APP}/remote.txt ${SLINGER_CONF}/sample_remote.txt
	
	python3 -u ${SLINGER_APP}/slingbox_server.py ${SLINGER_CONF}/config.ini
fi

exit


echo "=== Exiting aircast run ==="
